# This is a config file for automatically updating the project configuration
# based on changes made in the https://github.com/TeamDev-IP/Configs repository.

# The list of configs applied to this project.
# Order matters: later configs will overwrite conflicting changes made by earlier ones.
configs:
  - name: java
  - name: open-source-copyright

# The GitHub username of the developer who will be assigned to the PR and responsible for merging it.
assignee: vladimir-ikryanov
