# This is a config file for automatically updating the project configuration
# based on changes made in the https://github.com/TeamDev-IP/Configs.

# The GitHub usernames of the developers who will be requested to review the PR with the config changes.
# The first developer in the list will also be assigned to the PR and responsible for merging it.
reviewers:
  - Dmytro-Fedoryshyn

# The list of configs, applied to this project.
# The configs will be applied one-by-one in the specified order,
# resulting in conflicting changes being overwritten by subsequent configs.
configs:
  - java-gradle
  - java-open-source
